### ISSUE TITLE
Can't try with Expo

### ISSUE THREAD

**Issue by jacklam718** [IjzerenHein/react-native-magic-move#1]
### Expected behaviour
Try with Expo

### Show Actual behaviour

Getting this error message when try it with Expo: The experience you requested is not viable by you. You will need to log in or ask the owner to grant you access.

<img src="https://user-images.githubusercontent.com/5494638/50990601-6e609800-154d-11e9-8ccb-83539b52cd62.PNG" width=300 />

### I'm seeing this behaviour on

N/A

### Provide the code

N/A

**Comment by jacklam718** [comment]
- Yes I've logged in
- I think my Expo is latest version (at least I can't see available update from AppStore)
- My Expo version: `v2.10.0.105122`

**Comment by IjzerenHein** [comment]
I just checked gain, but the project really is a public expo project. I tried it on my GF's phone and it worked for her. I'm pretty sure it's something with Expo. Have you tried googling for similar problems?

**Comment by IjzerenHein** [comment]
This describes the problem
https://github.com/expo/expo/issues/2724

**Comment by brentvatne** [comment]
you can use an ios simulator to open it, if you don't have the expo client in the simulator you can run `yarn global add expo-cli && expo install:ios`
