### ISSUE TITLE
Trying to resolve view with tag 327 which doesnt exist

### ISSUE THREAD

**Issue by lmh87883819** [IjzerenHein/react-native-magic-move#12]
I use with flatlist.it works well in ios,but doesn't work in android,i dont know how to resolve it,please help me,thanks!

**Comment by IjzerenHein** [comment]
Hi, can you share a code example that triggers the problem?

**Comment by IjzerenHein** [comment]
Hi, could you try the latest 0.6.4 version? It fixes some native problems on Android. You can install it via `react-native-magic-move@next`.
https://github.com/IjzerenHein/react-native-magic-move/releases/tag/v0.6.4

**Comment by lmh87883819** [comment]
thank you😊
