### ISSUE TITLE
Question: support for react-native-navigation?

### ISSUE THREAD

**Issue by oferRounds** [IjzerenHein/react-native-magic-move#15]
Way to go for this awesome library!

I wanted to know if it can be used with [react-native-navigation](https://github.com/wix/react-native-navigation)?

**Comment by IjzerenHein** [comment]
Hi, I've answered this one in #13. Closing because of duplicate

**Comment by oferRounds** [comment]
Oh sorry, I was looking but somehow missed it. Thank you!
