### ISSUE TITLE
RNMagicMove.podspec position

### ISSUE THREAD

**Issue by erlangzhang** [IjzerenHein/react-native-magic-move#17]
please move ios/RNMagicMove.podspec to /RNMagicMove.podspec
for react-native link react-navigation-magic-move

**Comment by IjzerenHein** [comment]
Hi, I've added the`.podspec` file to the project. Could you give it a test by installing `react-native-magic-move@next` ? This will install the preliminary v0.6.3 version. If that works for you I will make a public release out of it. Cheers

**Comment by IjzerenHein** [comment]
Closing due to being resolved and non activity
