### ISSUE TITLE
iOS build fails on RN 0.60.x with native dependencies

### ISSUE THREAD

**Issue by rgommezz** [IjzerenHein/react-native-magic-move#20]
### Expected behaviour
Building a RN@0.60 project that uses `react-native-magic-move` and its native dependencies successfully on iOS.

### Show Actual behaviour

RN relies on CocoaPods from v0.60 onwards to autolink native dependencies.

Doing:

```bash
$ cd ios
$ pod install
```

I get a warning saying this library does not support autolinking.

I tried the classical manual link steps, but I get odd errors with React `*.h` files not found. My guess is that this library tries to fetch React deps from `libraries` folder instead of the newly pods I guess, but I am not sure.

Do you foresee an easy fix to support Cocoapods in the upcoming days?

### I'm seeing this behaviour on

- Device: any iOS simulator
- Routing/transition library: `react-navigation@3.11.0`
- React-native version: v0.60.4
- react-native-magic-move version: v0.6.5

**Comment by IjzerenHein** [comment]
Hi. Thanks for letting me know. I've fixed the issue and released a new version:
https://github.com/IjzerenHein/react-native-magic-move/releases/tag/v0.6.6
Let me know whether it works for you now.
cheers

**Comment by rgommezz** [comment]
Thanks, works as expected!
