### ISSUE TITLE
Error while updating property 'transform' of a view managed by: RCTView null translateX

### ISSUE THREAD

**Issue by hesusdios** [IjzerenHein/react-native-magic-move#3]
### Expected behaviour

Should render component on screen

### Show Actual behaviour

![image](https://user-images.githubusercontent.com/25207023/51179842-f08eea80-18c6-11e9-947a-56e1b3280d99.png)

### I'm seeing this behaviour on

- Device: (Samsung s8, physical device)
- Routing/transition library: (e.g. react-navigation)
- React-native version: v0.0.0
- react-native-magic-move version: v0.0.0

### Provide the code

![image](https://user-images.githubusercontent.com/25207023/51180014-714de680-18c7-11e9-9722-3801631fa748.png)

**Comment by IjzerenHein** [comment]
Hi, you need to set  `<MagicMove.Scene>` around your navigation screen, not the list-item. Let me know whether that worked

**Comment by IjzerenHein** [comment]
Is this still active?

**Comment by hesusdios** [comment]
Sorry I didn't see this notification. Bedankt! I will try it out and let you know.
